
seed: 42

paths:
  base: /content/FDN_medical_images
  data: /content/FDN_medical_images/data
  raw: /content/FDN_medical_images/data/raw
  raw_ham10000: /content/FDN_medical_images/data/raw/HAM10000
  splits: /content/FDN_medical_images/data/HAM10000_splits
  preprocessed: /content/FDN_medical_images/data/preprocessed
  results: /content/FDN_medical_images/results
  logs: /content/FDN_medical_images/results/logs
  models: /content/FDN_medical_images/results/models

preprocessing:
  image_size: 224
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]

cv:
  n_folds: 5
  shuffle: true
  stratify_by: lesion_id
  random_state: 42

training:
  epochs: 100
  batch_size: 32
  learning_rate: 1e-4
  early_stopping_patience: 10
  optimizer: adamw
  weight_decay: 0.01

loss:
  type: cross_entropy
  class_weights: true

augmentation:
  horizontal_flip: true
  vertical_flip: false
  rotation_range: 15
  brightness_range: [0.8, 1.2]
  zoom_range: 0.1

logging:
  log_interval: 10
  save_checkpoints: true
  checkpoint_interval: 5

misc:
  num_workers: 4
  pin_memory: true
